### ISSUE TITLE
[Feature Requests] Search result context + Extra UI Options

### ISSUE THREAD

**Issue by yoofie** [reduf/search#19] opened 2023-04-13 16:53 UTC
Hello. First of all, thanks for this tool. . This tool is very useful because it launches & runs fast. I use this instead of launching VS Code or using the ripgrep CLI when searching for text. I was going to create my own version before I found this.

So I have some feature requests or suggestions and I figured I would put it in one issue:

1) **Before & after result context.** 
RipGrep (and VS Code) offer the ability to display the before & after context of the search result. This would be super handy if the user had the option to display the result context in the results table.

2) **Auto focus to search text field when launching the app**. 
I have this program bound to a global keyboard shortcut, but when the program launches, I need to use the CTRL + F keyboard shortcut to focus on the search text field. It would be cool if the app auto focuses to the search text field by default upon startup. Bonus points if you can make the auto focus behavior user customizable. Auto focus to the patterns field or paths field, for example.

3) **Option to strip/remove redundant path in the result table.** 
When searching in some directory, the results file column shows the whole path instead of the relative path. It would be cool if had an option to remove the redundant part so that the File column takes less visible screen space. See image:

![image](https://user-images.githubusercontent.com/1758416/231828528-fa7b7c6b-d8fd-4d08-af18-a5df003e24a0.png)

4) Related to point number 3 above. Since the File column takes up alot of space, give us an option to auto size the column width so that all the text is visible? This is only an issue because of the long file paths.

I quickly scanned the code and these should be possible. What do you think?

**Comment by reduf** [comment] 2023-04-13 17:55
Hey, so I'll comment in order.

1. Absolutely, I think it would be useful and it shouldn't be too hard with the ripgrep code used. There is this weird callback scheme, but still should not be too hard. I'm not sure what we need to have it work correctly with imgui, but should be somewhat straightforward. There is a bunch of small details about how it knows how many entries to render.
2. That's a small detail, but seems to make sense.
3. I initially tried something like that, but I'm not sure how to always do it. So, if there is a single paths that is searched, it seems easy enough. If there is multiple paths searches, what should be the behavior? Should it only be when a single paths is specified? An other idea I had was to only render the path for the first entry of the file and leave empty under, but when you have a lot of entry and the user scroll, you need to know that and print the path on the first visible entry.
4. I know you can double click on the separator between File & Line and it will auto adjust. I don't know if there is a good way to do it with Imgui, but if you have it, that could definitely be useful. We should still check how it feels, especially when scrolling as thing my start to jump around. Overall, I think for point 4 it might be a bit hard to do nicely.

**Comment by reduf** [comment] 2023-04-15 09:47
If you pull latest, I added quite a few things.

1. We now support the context and that includes grouping if there is two matches where the context would overlap. That's thanks to ripgrep, nothing I did extra.
2. We do background coloring to make it easier to read. I don't do it when there is no context as it seems to only be noise.
3. You now have a setting to only show the filename. If this setting is on and you over a file name, you have a full path.
4. The search query is now focused by default.
5. The column size resize dynamically.

I didn't do the thing to show the relative path yet, I think it's a good idea, but need to do it.

**Comment by reduf** [comment] 2023-04-15 10:24
So I had a look and removing redundant path require changes in the crates ignore from ripgrep. Overall, when doing a directory walk, it returns the path relative to the given search which is by default `./`, although `./` is stripped when printing.

The issue is that we can't specify a relative path (because it would be relative to what?) and when we process a file to find all matches, we don't know how the walk came to this file, so we don't know which prefix to remove.

In theory, we should be able to add that to the ignore crate and add this option. I'll close this issue and track this last problem in a different issue, since most feature requests were addressed.

**Closed by reduf** 2023-04-15 10:24 UTC

**Comment by yoofie** [comment] 2023-04-15 17:21
Oh wow - that was quick. Thanks for the awesome update! This basically addresses all my issues.

Only one minor feature that you can potentially add in the future: Make the default search context value user adjustable in the settings window or in `search.conf`. Default is zero but I imagine most people who use the context have it set to some non-zero value by default. For my own needs, I just updated it in the source code and built my own copy of the program.

Anyway - thanks for the quick responses & updates. Awesome tool - very appreciated.

**Comment by reduf** [comment] 2023-04-15 19:58
I did think about it, but it doesn't quite fit the current setup. For instance, how would that work when you have two tabs with different values?

That said, saving this value would be useful and I think it would better fit with the ability of saving the tab states to the disk.
